apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: microservices
data:
  ORDER_SERVICE_URL: "http://order-service.microservices.svc.cluster.local:8001"
  NOTIFICATION_SERVICE_URL: "http://notification-service.microservices.svc.cluster.local:8002"
