apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Observability stack (Prometheus, Grafana, Loki)
  sourceRepos:
    - "https://prometheus-community.github.io/helm-charts"
    - "https://grafana.github.io/helm-charts"
    - "https://github.com/lilkhalatyan/k8s-platform-aws.git"
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: monitoring.coreos.com
      kind: "*"
